version: 2.1
jobs:
  build-lts:
    docker:
      - image: "ubuntu:latest"
    resource_class: medium
    environment:
      CI_PIPELINE_NUMBER: << pipeline.number >>
    steps:
      - run:
          name: Reload apt index
          command: 'apt-get update'
      - run:
          name: Configure apt cache
          command: |
              echo 'APT::Keep-Downloaded-Packages "true";' >/etc/apt/apt.conf.d/01keep-debs
              echo 'Binary::apt::APT::Keep-Downloaded-Packages "true";' >>/etc/apt/apt.conf.d/01keep-debs
      - run:
          name: Remove apt cache purge configuration
          command: rm /etc/apt/apt.conf.d/docker-clean
      - run:
          name: Install basic utilites
          command: 'apt-get install -y git ca-certificates'
      - checkout
      - run:
          name: Check out submodules
          command: 'git submodule update --init --recursive --jobs 4'
      - restore_cache:
          keys:
              - apt-lts-cache-{{ checksum ".circleci/install-dependencies.sh" }}
              - apt-lts-cache
      - run:
          name: Install dependencies
          command: './.circleci/install-dependencies.sh'
      - run:
          name: Clean outdated packages from apt cache
          command: apt-get autoclean
      - save_cache:
          key: apt-lts-cache-{{ checksum ".circleci/config.yml" }}
          paths:
              - "/var/cache/apt/archives"
      - run:
          name: Build and create bundle
          command: './.circleci/build-and-package.sh'
      - when:
          condition:
            equal: [ main, << pipeline.git.branch >> ]
          steps:
            - run:
                name: Publish to testing PPA
                command: |
                    ./.circleci/ppa-publish.sh \
                      "ppa:v19930312/linuxmotehook2-testing" \
                      "$(meson introspect /tmp/build --projectinfo | jq -r .version)+ci${CI_PIPELINE_NUMBER}" \
                      "New upstream commit"
      - when:
          condition: << pipeline.git.tag >>
          steps:
            - run:
                name: Publish to release PPA
                command: |
                    ./.circleci/ppa-publish.sh \
                      "ppa:v19930312/linuxmotehook2" \
                      "$(meson introspect /tmp/build --projectinfo | jq -r .version)" \
                      "New upstream release"
      - store_artifacts:
          path: /tmp/artifacts

  build-rolling:
    docker:
      - image: "ubuntu:rolling"
    resource_class: medium
    environment:
      CI_PIPELINE_NUMBER: << pipeline.number >>
    steps:
      - run:
          name: Reload apt index
          command: 'apt-get update'
      - run:
          name: Configure apt cache
          command: |
              echo 'APT::Keep-Downloaded-Packages "true";' >/etc/apt/apt.conf.d/01keep-debs
              echo 'Binary::apt::APT::Keep-Downloaded-Packages "true";' >>/etc/apt/apt.conf.d/01keep-debs
      - run:
          name: Remove apt cache purge configuration
          command: rm /etc/apt/apt.conf.d/docker-clean
      - run:
          name: Install basic utilites
          command: 'apt-get install -y git ca-certificates distro-info lsb-release'
      - run:
          name: Halt if we are LTS
          command: |
              if [[ $(ubuntu-distro-info -s) == $(lsb_release -c) ]]; then
                  echo "We are LTS - halting!"
                  circleci-agent step halt
              fi
      - checkout
      - run:
          name: Check out submodules
          command: 'git submodule update --init --recursive --jobs 4'
      - restore_cache:
          keys:
              - apt-rolling-cache-{{ checksum ".circleci/install-dependencies.sh" }}
              - apt-rolling-cache
      - run:
          name: Install dependencies
          command: './.circleci/install-dependencies.sh'
      - run:
          name: Clean outdated packages from apt cache
          command: apt-get autoclean
      - save_cache:
          key: apt-rolling-cache-{{ checksum ".circleci/config.yml" }}
          paths:
              - "/var/cache/apt/archives"
      - run:
          name: Build and create bundle
          command: './.circleci/build-and-package.sh'
      - when:
          condition:
            equal: [ main, << pipeline.git.branch >> ]
          steps:
            - run:
                name: Publish to testing PPA
                command: |
                    ./.circleci/ppa-publish.sh \
                      "ppa:v19930312/linuxmotehook2-testing" \
                      "$(meson introspect /tmp/build --projectinfo | jq -r .version)+ci${CI_PIPELINE_NUMBER}" \
                      "New upstream commit"
      - when:
          condition: << pipeline.git.tag >>
          steps:
            - run:
                name: Publish to release PPA
                command: |
                    ./.circleci/ppa-publish.sh \
                      "ppa:v19930312/linuxmotehook2" \
                      "$(meson introspect /tmp/build --projectinfo | jq -r .version)" \
                      "New upstream release"
      - store_artifacts:
          path: /tmp/artifacts

workflows:
  version: 2
  build-all:
    jobs:
      - build-lts:
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+$/
      - build-rolling:
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+$/
